version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: 'mongodb-vopak'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - mongo-net-vopak

  mongo-express:
    image: mongo-express:latest
    container_name: 'mongo-express-vopak'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - mongo-net-vopak
    depends_on:
      - mongo


networks:
  mongo-net-vopak:
    driver: bridge