org: saeeduni68
service: vopak-demo-serverless
app: vopak-demo

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 10

functions:
  vopak:
    handler: index.handler
    description: 'description'
    timeout: 30
    events:
      - http:
          path: /info
          method: any
          cors: true

      - http:
          path: /api/currentweather/{cname}
          method: get
          cors: true
      - http:
          path: /api/currenttempincovilha
          method: get
          cors: true

      - http:
          path: /api/avgtemp/{cname}/{month}
          method: get
          cors: true
      - http:
          path: /api/avgtempinsfax
          method: get          
          cors: true


  multiplyNumbersForTest:
    handler: handler.multiplyNumbersForTest
    events:
      - http:
          integration: lambda
          path: multiply-number-for-test
          method: get
          cors: true



plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-mocha-plugin